[theme]
primaryColor = "#fbbf24"
backgroundColor = "#1e1b4b"
secondaryBackgroundColor = "#312e81"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false